name: Sync with upstream
on:
  schedule:
    - cron: "30 22 * * *"
  workflow_dispatch:

jobs:
  merge:
    name: Sync with upstream
    env:
      super_secret: ${{ secrets.PAT }}
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
        if: ${{ env.super_secret == '' }}
        name: Checkout using Github Token
        with:
          fetch-depth: 0

      - uses: actions/checkout@v3
        if: ${{ env.super_secret != '' }}
        name: Checkout using Personal Token
        with:
          fetch-depth: 0
          token: ${{ secrets.PAT }}

      - name: Setup git
        run: |
          git config --global user.email ${{ github.repository_owner_id }}+${{ github.repository_owner }}@users.noreply.github.com
          git config --global user.name ${{ github.repository_owner }}
          git config --global pull.rebase false
          git config merge.theirs.driver "cp -f %B %A"

      - name: Merge changes from main
        run: |
          git pull https://github.com/YT-Advanced/WSA-Script main --no-edit

      - name: Compare changes
        id: compare
        run: |
          echo "changes=$(git diff --name-only HEAD origin/main | grep -v '.github/workflows/custom_build.yml' | grep -v '.github/workflows/build.yml' | grep -v '.github/workflows/lock-closed-issues.yml' | grep -v '.github/workflows/lock.yml' | grep -v '.github/workflows/merge_upstream.yml' | grep -v '.github/workflows/shellcheck.yml' | grep -v '.github/workflows/update.yml' | grep -v '.github/workflows/workflow.yml' | tr '\n' ' ')" >> $GITHUB_OUTPUT

      - name: Restore workflow file
        if: ${{ env.super_secret == '' && steps.compare.outputs.changes != '' }}
        run: |
          git restore --source=HEAD~1 .github/workflows/build.yml .github/workflows/custom_build.yml .github/workflows/merge_upstream.yml .github/workflows/update.yml .github/workflows/workflow.yml .github/workflows/shellcheck.yml .github/workflows/lock.yml .github/workflows/lock-closed-issues.yml
          git commit -a -m "Revert changes"

      - name: Push all changes
        if: ${{ steps.compare.outputs.changes != '' }}
        run: |
          git push origin main --force

      - name: Delete old workflow run using Github Token
        if: ${{ env.super_secret == '' }}
        uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{ github.token }}
          repository: ${{ github.repository }}
          retain_days: 0
          keep_minimum_runs: 0
          delete_workflow_pattern: "Sync with upstream"

      - name: Delete old workflow run using Personal Token
        if: ${{ env.super_secret != '' }}
        uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{ secrets.PAT }}
          repository: ${{ github.repository }}
          retain_days: 0
          keep_minimum_runs: 0
          delete_workflow_pattern: "Sync with upstream"
